spring.application.name=ancients
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
logging.level.root=WARN

spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

#------RAILWAY---------
# Railway/Cloud port
server.port=${PORT:8080}

# MySQL (env vars)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
